### ISSUE TITLE
Figure out a proper publish workflow

### ISSUE THREAD

**Issue by MasterKale** [MasterKale/SimpleWebAuthn#278]
I struggled to publish v6.2.1 in the wake of #276. `lerna bootstrap` generated **package-lock.json** files in each of the packages' folders, and then `lerna publish` errored out because the files were in **.gitignore**:

```
? Are you sure you want to publish these packages? Yes
lerna info execute Skipping releases
lerna ERR! Error: Command failed with exit code 1: git add -- packages/server/package.json packages/server/package-lock.json lerna.json package-lock.json
lerna ERR! The following paths are ignored by one of your .gitignore files:
lerna ERR! packages/server/package-lock.json
lerna ERR!     at makeError (/Users/matt/Developer/simplewebauthn/node_modules/execa/lib/error.js:60:11)
lerna ERR!     at handlePromise (/Users/matt/Developer/simplewebauthn/node_modules/execa/index.js:118:26)
lerna ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! Error: Command failed with exit code 1: git add -- packages/server/package.json packages/server/package-lock.json lerna.json package-lock.json
lerna ERR! The following paths are ignored by one of your .gitignore files:
lerna ERR! packages/server/package-lock.json
lerna ERR!     at makeError (/Users/matt/Developer/simplewebauthn/node_modules/execa/lib/error.js:60:11)
lerna ERR!     at handlePromise (/Users/matt/Developer/simplewebauthn/node_modules/execa/index.js:118:26)
lerna ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! lerna Command failed with exit code 1: git add -- packages/server/package.json packages/server/package-lock.json lerna.json package-lock.json
lerna ERR! lerna The following paths are ignored by one of your .gitignore files:
lerna ERR! lerna packages/server/package-lock.json
```

I managed to get v6.2.1 published with the following steps:

1. Run `npm run clean` to remove all **node_modules/** and **package-lock.json** files in **packages/**
2. Run `lerna bootstrap --hoist` to hoist all dependencies into root **node_modules/**
3. Discard the changes made to the root **package-lock.json** from Step 2
4. Run `lerna publish` to finally get the latest versions published.

This is ridiculous, am I just monorepo'ing wrong? There's gotta be a better way.

Maybe I `rm` the **packages/**/package-lock.json** files created by the non-hoisted `lerna bootstrap` before `lerna publish` runs?

**Comment by MasterKale** [comment]
I just played around a bit, I think something like this will work:

```
lerna bootstrap && rm ./packages/**/package-lock.json && lerna publish
```

It at least got me to the OTP prompt in `lerna publish`, which means the build succeeded. This feels a bit irresponsible somehow, though; I should try and ask someone more familiar with Lerna what they'd do in this situation.

**Comment by MasterKale** [comment]
Well whaddayaknow, look at this issue from _2019_: https://github.com/lerna/lerna/issues/2391

The latest comment from three weeks ago basically confirms my proposed approach above:

> Commenting in case this helps someone.
> I got around this in CI by simply deleting the package-lock.json file before the lerna publish cmd, which for us was the last action in the release stage anyway.
> This is probably only most useful in CI environments
