### ISSUE TITLE
TypeError: Invalid JWK EC key

### ISSUE THREAD

**Issue by netmiller** [MasterKale/SimpleWebAuthn#656]
Trying to upgrade my login-functions from 8.3.5 -> to v.12.x.

I got error message :

````
login-verify-catch-error: TypeError: Invalid JWK EC key
    at Object.ecImportKey (node:internal/crypto/ec:243:27)
    at SubtleCrypto.importKey (node:internal/crypto/webcrypto:621:10)
    at importKey (/Users/esa/devel/arkeserver/node_modules/@simplewebauthn/server/script/helpers/iso/isoCrypto/importKey.js:8:29)
    at async verifyEC2 (/Users/esa/devel/arkeserver/node_modules/@simplewebauthn/server/script/helpers/iso/isoCrypto/verifyEC2.js:62:17)
    at async Object.verifyAuthenticationResponse (/Users/esa/devel/arkeserver/node_modules/@simplewebauthn/server/script/authentication/verifyAuthenticationResponse.js:157:19)
    at async exports.loginVerify (/Users/esa/devel/arkeserver/lib/fidoSWA.js:516:29)
    at async /Users/esa/devel/arkeserver/routes/fidoRtr.js:330:16 {
  code: 'ERR_CRYPTO_INVALID_JWK'
}
````

NodeJS version is v22.9.0. 

And I'm using plain NodeJS with `require` and __not TypeScript__ at all (=old project and not need for TypeScript at a moment).

````
const swaServer = require('@simplewebauthn/server');
const swaHelper = require('@simplewebauthn/server/helpers');
. . . etc
````

Any idea what to look at my code. Can it be some `isoBase64URL` issue or something else.

**Comment by MasterKale** [comment]
Hello @netmiller, can you please share some sample code of how you're calling `verifyAuthenticationResponse()`, including the response and public key? And to confirm, responses verify fine with v8 but break once you update to v12?

**Comment by netmiller** [comment]
Found the bug; it was just a typo in my own code. 

Expression `..... = isoBase64URL.fromBuffer(_regInfo.credential.publicKey);` was missing `base64`.  
Fixed with `.... = isoBase64URL.fromBuffer(_regInfo.credential.publicKey, 'base64');

That typo was while saving registration info. Now it's working ok.

**Comment by netmiller** [comment]
Closing this. Error happened while login-verification, and the message was something confusing.
Thanks anyway .
